### PR TITLE
Sort table keys in cleanup_table_ddl()

### PR DESCRIPTION
**Pull request by nicolashahn**
Context: When running an alembic upgrade that removes a key (where there are multiple keys and the key is not the last one added), and then running the downgrade that replaces it, the `SHOW CREATE TABLE` output differs because the removed key has now been placed after the other keys. This change is to ensure that the output stays consistent by sorting the lines that begin with `KEY` in each table DDL. 

This will change the output of `ddldump` compared to the previous version, which may not be ideal for some users, so the version has been incremented by a minor version.

### CODE REVIEW

**Comment by lra** [comment]
Can you try pushing again to trigger CCI?

**Comment by lra** [comment]
FTR, it won't pass until https://github.com/percolate/ddldump/pull/11 is merged.

**Comment by lra** [comment]
@nicolashahn can you fix the last CI error?

**Comment by nicolashahn** [comment]
@lra @dimitrylukashov Did the flake8 fixes, but the mysql error is an intended consequence of the change

**Comment by dimitrylukashov** [comment]
@nicolashahn that's fine, just manually update the mysql dumpfile to reflect the correct order of indices. It would be good to add a similar case to the postgresql dumpfile.

**Comment by nicolashahn** [comment]
@dimitrylukashov looks like this change only affects mysql dumps, or at least only the mysql test db here.

**Pull request merged**
